### ISSUE TITLE
请教下画布

### ISSUE THREAD

**Issue by JakeWoki** [BibBin/taro-poster-builder#1]
```ts
          const pageInstance = Taro.getCurrentInstance()?.page || {} // 拿到当前页面实例
          const query = Taro.createSelectorQuery().in(pageInstance) // 确定在当前页面内匹配子元素
          query
            .select(`#${canvasId}`)
            .fields({ node: true, size: true, context: true }, (res) => {
              const canvas = res.node
              const ctx = canvas.getContext("2d")
              resolve({ ctx, canvas })
            })
            .exec()
```
这样获取画布感觉挺麻烦的，不能用Taro.createCanvasContext的吗？

**Comment by BibBin** [comment]
> ```ts
>           const pageInstance = Taro.getCurrentInstance()?.page || {} // 拿到当前页面实例
>           const query = Taro.createSelectorQuery().in(pageInstance) // 确定在当前页面内匹配子元素
>           query
>             .select(`#${canvasId}`)
>             .fields({ node: true, size: true, context: true }, (res) => {
>               const canvas = res.node
>               const ctx = canvas.getContext("2d")
>               resolve({ ctx, canvas })
>             })
>             .exec()
> ```
> 
> 这样获取画布感觉挺麻烦的，不能用Taro.createCanvasContext的吗？



> ```ts
>           const pageInstance = Taro.getCurrentInstance()?.page || {} // 拿到当前页面实例
>           const query = Taro.createSelectorQuery().in(pageInstance) // 确定在当前页面内匹配子元素
>           query
>             .select(`#${canvasId}`)
>             .fields({ node: true, size: true, context: true }, (res) => {
>               const canvas = res.node
>               const ctx = canvas.getContext("2d")
>               resolve({ ctx, canvas })
>             })
>             .exec()
> ```
> 
> 这样获取画布感觉挺麻烦的，不能用Taro.createCanvasContext的吗？

微信小程序官方：从基础库 [2.9.0]开始，本接口停止维护
而且createCanvasContext只是微信小程序的API
